Create sidebar
yossdev/mypoints-client pull request #4
Opened 2021-12-18 05:50 UTC by adzanfsw

sidebar dah jadi man-teman ..

2021-12-18 17:27 UTC, yossdev reviewed
Ga jd pakai atomic design? @adzanfsw @MohammadWawan

2021-12-19 04:54 UTC, adzanfsw commented
ga jadi kaya nya deh ..

2021-12-19 07:23 UTC, yossdev commented
> ga jadi kaya nya deh ..

kenapa?

2021-12-19 10:30 UTC, MohammadWawan requested changes
nanti tak approve yang udah jadi ya jar

2021-12-20 01:13 UTC, adzanfsw commented
cek sidebar di endpoint /dashboard

2021-12-20 07:36 UTC, yossdev requested changes
masih ada yg perlu diperbaiki sama penamaan file juga.

2021-12-20 07:36 UTC, yossdev commented on src/components/UI/molecules/usermenu.jsx
> +                    <img alt="avatar" className="mr-2" src={"https://kredithptangcity.com/wp-content/uploads/2020/11/user.png"} width={35} />
ini jgn ngambil dari url

2021-12-20 08:34 UTC, yossdev approved these changes
oke udh aman

2021-12-20 08:35 UTC, MohammadWawan approved these changes

2021-12-20 08:36 UTC, merged